sgkit/api.py, sgkit/tests/test_api.py
Make all arguments to `create_genotype_call_dataset` keyword-only arguments (PEP 3102).
There is no particular natural order to the arguments and it would be easy to mix up the order; this change makes things more explicit, and allows the positional args to be reordered by the caller if desired.
=> Keyword-only arguments

.github/workflows/build.yml, README.md, setup.cfg, sgkit/api.py, sgkit/typing.py, sgkit/utils.py
I couldn't see a way of getting [mypy precommit](https://github.com/pre-commit/mirrors-mypy) to use the settings in `setup.cfg`, so instead I added a separate GH step to run mypy. This also means you have to run mypy yourself manually on your machine to check types.
Fixes #27.
=> Add mypy type checking to GitHub action

README.md, requirements-dev.txt
Benefits:
* make sure the versions of style checks are the same on all the checks (local, GH actions, etc)
* style check tools live in a separate venv
* less commands to run/remember
Regarding `mypy`, hopefully we can plug that into pre-commit as well sometime in the future.
=> Proposal: standardize style checks on pre-commit

sgkit/__init__.py, sgkit/api.py, sgkit/tests/test_api.py
A dosage representation is needed for https://github.com/pystatgen/sgkit-bgen/pull/1 - this is an example to help discussion in #21
=> Add create_genotype_dosage_dataset

setup.cfg, sgkit/tests/test_utils.py, sgkit/utils.py
This is needed by #40, as well as sgkit-bgen. I'll remove the function from sgkit-plink once this is merged.
=> Move encode_array to utils module from sgkit-plink

.github/workflows/build.yml, sgkit/stats/association.py, sgkit/tests/test_association.py
This PR contains some fairly minor adjustments/improvements to https://github.com/pystatgen/sgkit/pull/16 that allow for regression against multiple phenotypes.  Changes made:
- Shifts outcomes into batch dimensions of the algebra functions
- Makes the internal `linear_regression` function no longer hidden so that it can be used in other modules such as https://github.com/pystatgen/sgkit/issues/50
- Allows for covariates and traits to be specified as any combination of 1 or 2D data variables, all of which are concatenated column-wise
- Forces covariates and outcomes to be chunked along the variant dimension only, i.e. this won't scale to giant (100k+) numbers of either of those things
- Introduces a convention where all Dask operations are followed immediately by assertions on shape (and …
=> Extend GWAS linear regression for multiple phenotypes

setup.cfg, sgkit/__init__.py, sgkit/stats/aggregation.py, sgkit/testing.py, sgkit/tests/test_aggregation.py
This is an implementation for https://github.com/pystatgen/sgkit/issues/3. 
A few notes/questions:
- I was initially going to parameterize these tests across all array backends, and possibly mixtures of them.  I decided not to though because it doesn't seem like this is the right level to be validating ufunc reduce implementations that Xarray is ultimately dispatching to.  A convention I'd like to propose is that we don't write tests for multiple backends unless we're writing code that makes special accommodations for them (you'd need to to get 100% coverage anyhow).  I don't feel very strongly about that though so let me know what you guys think.
- We definitely need a convenient way to generate Dataset instances given that they'll often be the sole input to functions.  I put a method …
=> Allele count implementation

.github/workflows/build.yml, .github/workflows/docs.yml, .gitignore, README.md, docs/Makefile, docs/api.rst, docs/conf.py, docs/index.rst, requirements-dev.txt, setup.cfg, sgkit/api.py, sgkit/stats/association.py
This is the initial work to set up docs for the project, following discussion in #19.
- Uses Sphinx reStructuredText
- Currently very barebones, but shows the two top-level functions
- Uses the ReadTheDocs theme
- Hosted on GitHub pages at https://pystatgen.github.io/sgkit/ (at least for the moment)
- Docstring style is numpydoc, but Google-style docstrings are supported due to use of [sphinx.ext.napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html)
- Xarray types in the documentation are automatically converted to links (using [sphinx.ext.intersphinx ](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html)). Note that these types must be specified using reST, e.g. ``:class:`xarray.Dataset` ``
To generate and view docs locally:
```bash
cd docs …
```
=> Set up Sphinx documentation

sgkit/__init__.py, sgkit/api.py, sgkit/display.py, sgkit/tests/test_api.py, sgkit/tests/test_display.py
Fixes #37.
The `GenotypeDisplay` class just delegates to the Pandas dataframe, but it is probably worth having the wrapper to hide the implementation, and also because it allows us to customize (or completely change) the representation in the future.
=> Display genotypes function

setup.cfg, sgkit/tests/test_association.py, sgkit/tests/test_regenie.py, sgkit/tests/test_stats_utils.py, sgkit/tests/test_utils.py
Related: #74. This allows to use untyped decorators in tests, ex: hypothesis decorators.
=> Allow untyped decorators in tests

sgkit/api.py
This fixes #98 for `variant_id`, which I need for #104.
Should we change `sample_id` too, or do we always have the list of sample IDs up front?
=> Allow variant_id to be 'O' dtype to support variable length strings

docs/api.rst, sgkit/api.py, sgkit/stats/hwe.py, sgkit/stats/regenie.py
We need to make sure we add new functions to `docs/api.rst`. Perhaps a note in the contributor guide?
This fixes the build, but some of the formatting is not quite right. We should also visually check the docs whenever we add new functions to check that links, formatting etc are OK.
Fixes #212
=> Add missing API docs to Sphinx

setup.cfg, sgkit/stats/aggregation.py, sgkit/tests/test_aggregation.py, sgkit/tests/test_utils.py, sgkit/utils.py
This is an initial attempt to implement #103 for count allele functions. Does this look like the right direction?
=> Merge output variables with input dataset

sgkit/stats/hwe.py
https://github.com/pystatgen/sgkit/issues/222
=> Add nogil to hwe njit

sgkit/io/vcfzarr_reader.py
=> Workaround dask#6631

.mergify.yml
Related to: #100,  #218
Context: https://github.com/pystatgen/sgkit/pull/100#issuecomment-690319548
I still can't validate this config against #100 because https://github.com/pystatgen/sgkit/pull/100#issuecomment-690310074, so I would suggest waiting until we can validate that before merging this.
=> Fix mergify - new builds

.github/workflows/build.yml, docs/api.rst, requirements-dev.txt, setup.cfg, sgkit/__init__.py, sgkit/api.py, sgkit/stats/popgen.py, sgkit/tests/test_popgen.py
1. adds @jeromekelleher's code for converting from tskit trees to sgkit datasets, diversity, and divergence.
2. adds some minimal tests for the popgen stats.
Going forward in this PR I'd like to add:
- a test for ts_to_dataset
- windowing for popgen stats
I might save Fst and the others for a different PR.
=> [WIP] Popgen stats

docs/api.rst, requirements-dev.txt, setup.cfg, sgkit/__init__.py, sgkit/stats/pc_relate.py, sgkit/testing.py, sgkit/tests/test_pc_relate.py
Need to open a new PR to move to forked repo. Original #133 .
Changes:
* add `pc_relate` method
* add tests for `pc_relate`
* add validation data generator for `pc_relate`
* add `missing_pct` to `simulate_genotype_call_dataset`, to support missing data
=> Add PC Relate

requirements-dev.txt
Otherwise `conda install --file requirements-dev.txt` fails, we should probably test this in CI btw.
=> Conda doesn't like sklearn name, we need to use scikit-learn

docs/index.rst, docs/usage.rst, sgkit/stats/aggregation.py, sgkit/stats/association.py, sgkit/stats/hwe.py, sgkit/stats/pc_relate.py, sgkit/stats/regenie.py, sgkit/tests/test_hwe.py, sgkit/tests/test_regenie.py, sgkit/utils.py
=> Add merge parameter to method functions

.pre-commit-config.yaml, setup.cfg
Example of failure (from sgkit_vcf): https://github.com/pystatgen/sgkit-vcf/pull/11/checks?check_run_id=1112654920, reason `typing_extensions` are not in the ~requirements.~ setup.cfg.
Re: #255
=> Add missing typing_extensions to setup.cfg

.github/workflows/validation.yml, validation/gwas/method/pc_relate/Dockerfile, validation/gwas/method/pc_relate/README.md, validation/gwas/method/pc_relate/convert_plink_to_gds.R, validation/gwas/method/pc_relate/pc_relate.R, validation/gwas/method/pc_relate/requirements.txt, validation/gwas/method/pc_relate/run.sh, validation/gwas/method/pc_relate/validate_pc_relate.py
Depends on #228 (related: #24)
See: https://github.com/pystatgen/sgkit/pull/228#issuecomment-687607928 for context.
Todo:
This validation job currently tests sgkit_plink's `read_plink` + sgkit's `pc_relate` on HapMap data.
This is blocked on pystatgen/sgkit-plink#32.
=> Validation Suite (PC Relate)

.pre-commit-config.yaml
=> Remove seed-isort-config from pre-commit, since it's no longer needed.

.github/workflows/build.yml, .github/workflows/windows.yml, .mergify.yml, README.md, sgkit/stats/aggregation.py, sgkit/stats/regenie.py, sgkit/utils.py
This is a first attempt at #247.
* The main change is to use Miniconda (so we can install msprime easily on Windows).
* I couldn't get the pre-commit GH action to work with conda, so I ended up just calling the relevant commands directly.
* Added guards to only perform some actions (linting, doc checking, etc) for one matrix entry (Ubuntu/Python 3.7) 
* I had to skip some doctest checking, since on Windows it would show numpy arrays as `(array([0, 2], dtype=int64)` not `(array([0, 2])`. I'm not sure why this is happening exactly, but I couldn't see a way in numpy to control whether the dtype was displayed or not.
* We probably want to update `docs.yml` to use the same approach for consistency.
=> Windows CI

.github/workflows/build.yml, .github/workflows/docs.yml, docs/contributing.rst, requirements-dev.txt, requirements-doc.txt
The Windows CI build is [failing](https://github.com/pystatgen/sgkit/runs/1143067740) because it crossed with #261 which introduced dependencies that are not available in conda (for Windows). These are `scanpydoc` and `sphinx_autodoc_typehints`.
Since we don't build docs on Windows, I've split out the docs requirements, and not included them for the Windows build.
Fixes #247
=> Split out docs requirements so they don't need to be installed on Windows

.pre-commit-config.yaml, sgkit/display.py, sgkit/stats/hwe.py, sgkit/stats/popgen.py, sgkit/stats/utils.py, sgkit/tests/test_association.py, sgkit/tests/test_hwe.py, sgkit/tests/test_regenie.py, sgkit/tests/test_stats_utils.py
=> Remove unused errors (+ update pre-commit tools)

sgkit/io/vcfzarr_reader.py
Dask 2.18.0 has the fix included via https://github.com/dask/dask/pull/6632
This reverts commit ffd85e0e1f27478f550b188a53b597b71338d364.
=> Revert "Workaround dask#6631 (#246)"

.github/workflows/docs.yml
The docs build only gets run on push to master, so I missed this in #289.
=> Fix docs build after VCF merger

docs/api.rst, docs/index.rst, docs/user_guide.rst, docs/vcf.rst, sgkit/io/vcf/vcf_partition.py, sgkit/io/vcf/vcf_reader.py, sgkit/io/vcfzarr_reader.py
First (draft) attempt to include VCF docs for https://github.com/pystatgen/sgkit-vcf.
The API docs are included, but I needed to install the sgkit-vcf package ~~(with `--no-deps`, to avoid having to install cyvcf2, which is not needed for API signatures)~~.
Refs #54
=> Add VCF docs

.pre-commit-config.yaml, requirements-dev.txt, requirements.txt, setup.cfg, sgkit/__init__.py, sgkit/stats/pca.py, sgkit/stats/preprocessing.py, sgkit/tests/test_pca.py, sgkit/tests/test_preprocessing.py, sgkit/typing.py, sgkit/variables.py
Implementation for https://github.com/pystatgen/sgkit/issues/95.
Notes:
Some upstream fixes necessary for this were:
- Dask SVD broken for short-fat arrays (https://github.com/dask/dask/pull/6591)
- Dask SVD had poor performance on certain in-memory arrays (https://github.com/dask/dask/pull/6616)
- The svd_flip function in dask-ml (used by PCA/TruncatedSVD) would have forced in-memory evaluation, but it doesn't anymore (https://github.com/dask/dask/pull/6613)
- The fix for this also makes da.linalg.svd results consistent across platforms and input array chunkings 
- Dask-ml PCA classes force eager evaluation (https://github.com/dask/dask-ml/issues/740)
- Randomized SVD broken for small arrays (https://github.com/dask/dask/pull/6622)
- I added https://github.com/pystatgen/sgkit/issues/285 …
=> PCA implementation

sgkit/stats/hwe.py
Closes https://github.com/pystatgen/sgkit/issues/221.
Closes https://github.com/pystatgen/sgkit/issues/115.
The most unusual part of this function is that it is looking for some notion of ploidy and allele count without explicitly needing data related to either for the calculation it runs (it only requires genotype counts).  This works by adding parameters to the function that only need to be set if the same values cannot be found in the dataset dimensions.  That seemed like a reasonable approach to maximize safety -- let me know if you have other suggestions @ravwojdyla / @tomwhite.
=> HWE function updates

sgkit/stats/hwe.py, sgkit/tests/test_utils.py
These are small changes for https://github.com/pystatgen/sgkit/issues/336.
They improve the running time of a single test modestly and make it impossible for the test to fail the build again due to sporadic latencies.
I'm not sure what to do about deadlines in general (as mentioned in the issue), but perhaps disabling them when they become problematic is the best approach.
FYI these changes bring the total time for this test to run across all parameterizations down to ~1.5s (from ~6s), which is still annoyingly slow but a bit more palatable.
=> Remove deadline and improve speed of max_str_len test

sgkit/__init__.py, sgkit/stats/preprocessing.py, sgkit/tests/test_preprocessing.py, sgkit/variables.py
Issue #223 
Some notes:
- Adding a new top-level sub-module might be OTT but this doesn't really fit in `stats` or `model`.
- Currently this will always throw a merge warning which is a safe default but may be inconvenient. Is an argument to optionally silence merge warnings a good idea?
- This implementation will require some minor changes if/when #243 is resolved.
- Some discussion in issue #282 on handling partial genotypes in other functions.
=> Filter partial calls

sgkit/stats/popgen.py, sgkit/tests/test_popgen.py, sgkit/tests/test_window.py, sgkit/variables.py, sgkit/window.py
This is a proposal for #229, and is also related to #281.
* Adds a new `window` function that adds windowing information to a dataset (a `windows` dimension). This just adds fixed-size windows at the moment, and doesn't take contigs into account - both could be improved in the future.
* Adds a `window_statistic` function (similar scikit-allel's `moving_statistic`) that computes a statistic for each window (using Dask's `map_overlap` function) for use by method functions (i.e. this is not a user-facing function).
* Updates `diversity`, `divergence`, and `Fst` to use windows if present.
Sample usage:
```python
>>> ds = window(ds, size=25, step=25)
>>> fst_ds = Fst(ds, estimator="Nei")
>>> fst_ds
<xarray.Dataset>
Dimensions:              (alleles: 2, cohorts: 2, cohorts_0: 2, cohorts_1: 2, …
```
=> Fst windowing

sgkit/stats/aggregation.py, sgkit/stats/popgen.py, sgkit/tests/test_aggregation.py
Test that all allele counting functions are lazy.
Note that `test_count_variant_alleles__chunked` fails without the change in `count_variant_alleles`. 
Fixes #305.
=> Change count_variant_alleles to not reconstruct DataArray.

docs/api.rst, sgkit/__init__.py, sgkit/stats/aggregation.py, sgkit/stats/hwe.py, sgkit/stats/popgen.py, sgkit/tests/test_aggregation.py, sgkit/tests/test_popgen.py, sgkit/tests/test_utils.py, sgkit/utils.py
This addresses #286.
This is what I've implemented:
1. Methods declare only the variables that they use directly.
2. If the variable of the given name exists in the dataset it will be used for the computation.
3. If the variable doesn't exist then it will be computed if the variable name is the default, and added to the dataset.
4. An error is raised if the variable doesn't exist and it has a non-default name or it can't be computed (e.g. `call_genotype`).
These rules mean you can always call a method and it will compute (and retain) all intermediate variables:
```python
ds = pbs(ds)
```
To use non-default parameters for an intermediate step, you can do something like this:
```python
ds = Fst(ds, estimator="Nei")
ds = pbs(ds) # uses existing stat_Fst
```
This approach should also play …
=> Standardize intermediate variables

requirements-dev.txt
It seems there are multiple mentions of `scikit-allel` in the dev `requirements.txt`.
=> Remove duplicate scikit-allel from dev requirements

docs/api.rst, sgkit/__init__.py, sgkit/stats/aggregation.py, sgkit/stats/popgen.py, sgkit/variables.py
This is a documentation update to add some simple examples for popgen functions, and `count_cohort_alleles`. Also fixes some of the TODOs for #295.
=> Add popgen examples to docs

sgkit/distance/metrics.py, sgkit/stats/aggregation.py, sgkit/stats/popgen.py
Fixes #363
```
$ time python -c "import sgkit"
real	0m5.481s
user	0m5.960s
sys	0m0.527s
$ time python -c "import sgkit"
real	0m1.982s
user	0m2.520s
sys	0m0.471s
```
BTW @aktech I noticed that the `guvectorize` metric functions don't have `nopython=True` - do you think we should add it? (I could do it in this PR.)
=> Enable caching of compiled guvectorize functions

sgkit/tests/test_window.py, sgkit/variables.py, sgkit/window.py
=> Take contigs into account for fixed-size windowing

docs/api.rst, sgkit/__init__.py, sgkit/stats/popgen.py, sgkit/tests/test_popgen.py, sgkit/tests/test_utils.py, sgkit/utils.py, sgkit/variables.py, sgkit/window.py
This fixes #231.
* This PR depends on #377 for getting a haplotype representation of calls, so that should be merged first. The function there takes genotype calls of shape (variants, samples, ploidy) to (variants, haplotypes), where haplotypes=samples * ploidy.
* If the dataset is not windowed, the variants are assumed to be in a single window. This won't work for large numbers of variants (see discussion about hashing below), so we could choose not to support this and say that the input must be windowed. Would be good to hear thoughts about this @alimanfoo, @jeromekelleher.
* All of the H statistics work by computing statistics on the frequency of occurrences of each haplotype in a cohort. In scikit-allel, the haplotypes (columns of calls) are …
=> Garud H statistics

.github/workflows/docs.yml, docs/getting_started.rst
This is a follow on to #367. After this goes in I will make a few manual changes to the gh-pages branch to remove old top-level files, and add an HTML redirect from https://pystatgen.github.io/sgkit/.
=> Publish docs at https://pystatgen.github.io/sgkit/latest/

docs/contributing.rst, docs/getting_started.rst, docs/user_guide.rst, docs/vcf.rst, sgkit/io/bgen/__init__.py, sgkit/io/plink/__init__.py, sgkit/io/vcf/__init__.py
This moves the required Python versions to a more prominent position following https://github.com/pystatgen/sgkit/issues/367#issuecomment-728056891.
I have also removed the `--pre` option from the `pip install` commands. I misunderstood the meaning of this flag - I assumed that you had to include it to install *any* pre-release version, but that's not quite correct - if there are *only* pre-release versions available then pip will install the latest one of those, but if a stable version is available pip will favour that, even if it is older. This is discussed a bit more here: https://github.com/pypa/pip/issues/5503
So for example, at the moment users will get version 0.1.0a1 (whether they use `--pre` or not), but once we have released 0.1.0 and 0.2.0a1 (say), then users will get 0.1.0, …
=> Post 0.1.0a1 release doc fixes

sgkit/stats/popgen.py, sgkit/tests/test_popgen.py, sgkit/tests/test_window.py, sgkit/variables.py, sgkit/window.py
A simplification that addresses this comment: https://github.com/pystatgen/sgkit/pull/303#discussion_r508392377
=> Make window step default to window size

sgkit/__init__.py, sgkit/io/dataset.py, sgkit/tests/io/test_dataset.py
This fixes #298, and also incorporates some of the implementation from https://github.com/related-sciences/ukb-gwas-pipeline-nealelab/blob/4f862e31b8093d25fdaa8da7f841b9be8583cda4/scripts/gwas.py#L53-L71
Unlike #298 it does *not* rechunk the dataset before saving. I worry about having implicit rechunk methods that the user can't control since we have seen them perform poorly in some cases. For the moment I think it's preferable for the user to explicitly rechunk before saving. This is what I have been doing in the MalariaGEN notebooks, and Eric has too judging by [this example](https://github.com/related-sciences/ukb-gwas-pipeline-nealelab/blob/4f862e31b8093d25fdaa8da7f841b9be8583cda4/scripts/gwas.py#L228-L230).
I also haven't added `fsspec` support even though the GWAS pipeline uses it. …
=> Add load_dataset and save_dataset functions

sgkit/cohorts.py, sgkit/stats/popgen.py, sgkit/tests/test_cohorts.py, sgkit/tests/test_popgen.py
This addresses https://github.com/pystatgen/sgkit/issues/224#issuecomment-694350208 for specifying cohort subsets (for Garud H and PBS).
This is a draft since I haven't run it on MalariaGEN scale data yet, but I'd welcome any initial feedback.
=> Cohort subsets

docs/getting_started.rst
This covers the work done for #229 and #224 and related PRs.
We could certainly improve the user API for cohorts (and there are also improvements for windowing in #341), but this documents what we currently have at least.
=> Add docs for windowing and cohorts

sgkit/stats/pc_relate.py
I checked and this seemed to be the only one missing the space.
Fixes #339
=> Fix Returns spacing in documentation #339

.github/workflows/build.yml, .github/workflows/docs.yml, docs/api.rst, docs/conf.py, docs/contributing.rst, sgkit/io/plink/plink_reader.py, sgkit/stats/popgen.py
Enables nit picky mode when building Sphinx docs, which picks up some errors that were getting through before.
Fixes #86
=> Enable strict checking in Sphinx build #86

docs/api.rst, sgkit/__init__.py, sgkit/stats/aggregation.py, sgkit/tests/test_aggregation.py, sgkit/variables.py
=> Sample summary stats #29

sgkit/io/dataset.py, sgkit/tests/io/test_dataset.py
Fixes #395.
The problem with warnings about files not being closed was fixed in https://github.com/intake/filesystem_spec/pull/463. There hasn't been an `fsspec` release with that fix in yet, but I think we can merge this PR anyway, since I haven't seen it cause any problems (and @eric-czech has been using something equivalent in https://github.com/related-sciences/ukb-gwas-pipeline-nealelab/blob/4f862e31b8093d25fdaa8da7f841b9be8583cda4/scripts/gwas.py#L53-L71).
=> Use fsspec in load_dataset and save_dataset #395

docs/api.rst, sgkit/__init__.py, sgkit/io/bgen/bgen_reader.py, sgkit/stats/conversion.py, sgkit/tests/test_conversion.py
Closes https://github.com/pystatgen/sgkit/issues/346
=> Add method to convert genotype probabilities to calls

sgkit/io/vcf/vcf_partition.py, sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/data/no_genotypes.vcf, sgkit/tests/io/vcf/test_vcf_reader.py
This fixes a couple of problems found in #432.
=> Better errors for VCF files with no genotype information, or with missing contigs in the header

sgkit/model.py, sgkit/stats/aggregation.py, sgkit/stats/association.py, sgkit/stats/conversion.py, sgkit/stats/hwe.py, sgkit/stats/pc_relate.py, sgkit/stats/popgen.py, sgkit/stats/preprocessing.py, sgkit/stats/regenie.py, sgkit/utils.py, sgkit/variables.py, sgkit/window.py
This is a draft to show how it might work. I haven't converted all the docstrings yet, but will do if this looks OK.
Here is an example rendered dataset - note the `comment` attributes (they are hidden by default and can be viewed by clicking on the file icon):
I also checked that the Sphinx generated documentation is the same (note use of `dataclasses.field(repr=False)` so that the docstring does not show up as an attribute in the string representation of `ArrayLikeSpec`).
Fixes #393
=> Add docs for variables to xarray attributes #393

requirements.txt, setup.cfg
Re: #374 
There seem to be some dependencies between those two (like `dask.utils`), so if we pin `dask` (like in #426), we should also pin `distributed`, otherwise users (or in this case validation suite) will experience hard to debug failures. In case of the validation suite it was a cryptic:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'stringify' from 'dask.utils' (/Users/rav/miniconda3/envs/_sgkit_test/lib/python3.8/site-packages/dask/utils.py)
```
=> Use the same distributed as dask

sgkit/distance/api.py, sgkit/io/bgen/bgen_reader.py, sgkit/io/plink/plink_reader.py, sgkit/io/utils.py, sgkit/io/vcfzarr_reader.py, sgkit/stats/hwe.py, sgkit/stats/pca.py, sgkit/stats/regenie.py, sgkit/tests/test_pca.py, sgkit/tests/test_preprocessing.py, sgkit/window.py
Fixes #451 to unblock the build. We can probably improve the typing in some places with #452 (and/or when NumPy itself has more extensive type support).
=> Fix typing errors when upgrading to NumPy 1.20.0

requirements.txt, setup.cfg, sgkit/tests/test_pca.py, sgkit/tests/test_regenie.py
This will fail and should not be merged until there is a new release of dask-ml with https://github.com/dask/dask-ml/pull/767 in it.
=> Fix PCA tests running on Dask 2020.12.0

.github/workflows/benchmark.yml
Fixes this issue: https://github.com/pystatgen/sgkit/runs/2033236920
=> Push benchmarks to main branch instead of master

sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py
This exposes `alt_number` in the VCF reading API, just like [scikit-allel](https://scikit-allel.readthedocs.io/en/stable/io.html#allel.vcf_to_zarr) does.
=> Add alt_number to VCF reading

sgkit/tests/test_hwe.py
=> Xarray upstream fix

sgkit/io/utils.py, sgkit/io/vcf/vcf_reader.py, sgkit/io/vcfzarr_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/io/vcf/test_vcf_roundtrip.py
This changes the VCF reader to handle INFO and FORMAT fields of type Flag, Integer, or Float, and where number is 1, as suggested in #464.
A few things for discussion:
* Unlike scikit-allel which has a single `fields` list, I've created two, `info_fields` and `format_fields` to avoid ambiguities (like `DP`, which can apply to either), Alternatively, we could have a single list, and namespace them, e.g. `FORMAT/DP`.
* Naming. As it stands INFO fields are prefixed with `variant_`, and FORMAT fields with `call_`. So `call_DP` is an example. Do we want to add a renaming keyword (like scikit-allel has) so it could be renamed to e.g. `call_depth`?
* The `GT` FORMAT field is special since it is always included, even if `format_fields` doesn't include it. Should we make it optional?
* The …
=> VCF info and format fields

sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/io/vcf/test_vcf_roundtrip.py
Fixes #491.
This actually runs the tests against the other files. In doing so it exposed the fact that Number=G is not supported, so I added a way to exclude fields. There were a few other minor changes needed to get tests to pass.
I also removed two large files from the test, since they add ~120s to the test time. These would be better suited to testing in #478.
=> Add VCF exclude_fields parameter and fix test_all_fields #491

docs/api.rst, sgkit/__init__.py, sgkit/stats/aggregation.py, sgkit/stats/popgen.py, sgkit/tests/test_aggregation.py, sgkit/tests/test_popgen.py, sgkit/variables.py
Implements #499 
Some thoughts:
- This implementation aims to match that of the existing `diversity` method. One difference is that individual heterozygosity is undefined for haploid calls and hence any haploid calls won't contribute to the cohort observed heterozygosity.
- I have followed the use of `np.sum` in the windowed version of  `diversity` [(line)](https://github.com/pystatgen/sgkit/blob/master/sgkit/stats/popgen.py#L104). I couldn't find much discussion on this choice but I assume it's to avoid taking the mean prior to its use in other statistics?
- I'm not super happy with the length of `'stat_observed_heterozygosity'` as a variable name but `'stat_heterozygosity'` could easily be mistaken for the expected heterozygosity.
- I'm not sure if `aggregation.py` is the best place for …
=> Cohort Observed Heterozygosity

requirements.txt
=> Unpin Dask versions now that 2021.3.1 has been released and fixes #482

sgkit/stats/pca.py, sgkit/tests/test_aggregation.py, sgkit/tests/test_pca.py, sgkit/tests/test_variables.py, sgkit/variables.py
This fixes #506, and a couple of other related bugs that occur when an index is set and were found when working on #463:
* `var_name in ds` fails if the data variable `var_name` has been "moved" to be an index field of `ds`
* PCA doesn't work properly if there is an index set
Both of these cases are triggered by setting an index like this:
```python
ds = ds.set_index({"variants": ("variant_contig", "variant_position")})
```
See also #473
=> Fix various indexing bugs

sgkit/tests/test_import_star.py
I recently realised that you can refer to things that don't exist in the ``__all__`` list in ``__init__.py`` unless you do a test like this.
=> Test that import * works as expected.

.github/scripts/upstream_install.py
This should probably wait until https://github.com/pangeo-data/rechunker/pull/87 is in.
Fixes #549
=> Add rechunker to upstream tests #549

sgkit/stats/pc_relate.py, sgkit/tests/test_pc_relate.py
...to 'samples_0' and 'samples_1' for consistency with popgen.
Fixes #284
=> Rename dimensions 'sample_x' and 'sample_y' in PC relate

docs/api.rst, docs/contributing.rst, sgkit/stats/association.py, sgkit/stats/hwe.py, sgkit/stats/pc_relate.py, sgkit/stats/regenie.py, sgkit/tests/test_association.py, sgkit/tests/test_hwe.py, sgkit/tests/test_pc_relate.py, sgkit/tests/test_regenie.py, sgkit/variables.py, validation/gwas/method/pc_relate/validate_pc_relate.py, validation/gwas/method/regenie/unit_test_dev.ipynb
This fixes #295.
To find missing variables on the API page I ran:
```bash
for v in $(python -c 'import sgkit; print("\n".join(list(sgkit.variables.SgkitVariables.registered_variables.keys())))')
do
if ! grep "variables.${v}_spec" docs/api.rst >/dev/null; then
echo $v
fi
done
```
I've also renamed some variables for greater specificity/consistency:
* `{base,loco,meta}_prediction` -> `regenie_{base,loco,meta}_prediction`
* `variant_{beta,p_value,t_value}` -> `variant_linreg_{beta,p_value,t_value}`
* `genotype_counts` -> `genotype_count`
* `sample_pcs` -> `sample_pc`
This makes it clearer if we have both `variant_linreg_p_value` and `variant_hwe_p_value` in a dataset.
=> Review variables

.github/workflows/build.yml
The tests seems to be passing.
Fixes #310
=> Add support for Python 3.9 in the CI

validation/gwas/method/pc_relate/Dockerfile
Re: https://github.com/pystatgen/sgkit/issues/575
This should workaround the issue:
> Error in .install_repos(pkgs, old_pkgs, instPkgs = instPkgs, lib = lib,  : 
argument "force" is missing, with no default
=> Workaround install for 3.11 bioconductor

requirements.txt, setup.cfg
Fixes #590. It wasn't sufficient to just rename `make_meta` to `make_meta_util`, I had to also set `parent_meta`. 
I haven't tried to do anything for older versions of Dask - is is worth setting a minimum version in requirements?
The incompatible change was made in https://github.com/dask/dask/pull/7586.
=> Fix change in make_meta in Dask 2021.5.1 #590

setup.cfg, sgkit/tests/test_association.py
There are two parts to this fix: one that removes an assumption of dimension ordering (in `test_gwas_linear_regression__validate_statistics`), and another that ignores the two doctests that fail due to the `repr` having changed. These ignores can be removed once the next release of Xarray is made, so I'll open an issue to do that if this fix looks OK.
Fixes #583
=> Fix tests failing due to Xarray dims ordering change

docs/api.rst, sgkit/stats/pc_relate.py, sgkit/tests/test_pc_relate.py, sgkit/variables.py
Re: https://github.com/pystatgen/sgkit/issues/554
This allows the user to do sth like this:
```python
from sgkit import pc_relate, pca
skgit_dataset.pipe(pca, n_components=2)
.pipe(pc_relate)
```
=> Adjust pc_relate to our pca

.github/workflows/build-gpu.yml
Fixes #612 
dev numba isn't required. Also, there was bug as in numba is installed via requirements.txt anyways.
The tests passes now: https://github.com/aktech/sgkit/runs/2856192741?check_suite_focus=true
@ravwojdyla
=> Remove dev numba from GPU CI

.github/scripts/test_sgkit.py, .github/scripts/test_sgkit_bgen.py, .github/scripts/test_sgkit_plink.py, .github/scripts/test_sgkit_vcf.py, .github/workflows/wheels.yml, conftest.py
Fixes #606 
This workflow builds and tests wheels for each combination of the following (except VCF on Windows):
* IO: BGEN, PLINK, VCF
* Python: 3.7, 3.8, 3.9
* OS: Linux, MacOS, Windows
If successful it will push to test PyPi if the commit is tagged. I've tested this works by running it in the `test` branch in this repository. (See https://github.com/pystatgen/sgkit/runs/2830563755?check_suite_focus=true and https://test.pypi.org/project/sgkit/0.3.0a2/)
If there is no tag the wheels are still built and tested for every push to main - do we want that?
=> Deploy distribution artifacts to test PyPi on a tagged commit #606

docs/api.rst, docs/getting_started.rst, sgkit/__init__.py, sgkit/stats/ld.py, sgkit/stats/popgen.py, sgkit/tests/test_ld.py, sgkit/tests/test_popgen.py, sgkit/tests/test_window.py, sgkit/window.py
This is a draft implementation of the design sketched in https://github.com/pystatgen/sgkit/issues/341#issuecomment-847140397
There is still work to change existing `window` references to `window_by_index`. Also, the windowing code does not use Dask arrays, see #340 for follow on work to fix that.
=> Rename window to window_by_index, and add window_by_position

sgkit/io/vcf/vcf_reader.py, sgkit/model.py, sgkit/tests/io/vcf/data/no_genotypes_with_gt_header.vcf, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/io/vcf/test_vcf_roundtrip.py, sgkit/tests/test_variables.py, sgkit/variables.py
Fixes #618 
This change makes it possible to load GWAS summary statistics (#440) from https://github.com/MRCIEU/pygwasvcf/blob/master/tests/data/:
```
>>> import sgkit as sg
>>> from sgkit.io.vcf import vcf_to_zarr
>>> vcf_to_zarr("case.control.example.vcf.gz", "case.control.example.zarr", max_alt_alleles=1, fields=["INFO/*", "FORMAT/*"])
>>> ds = sg.load_dataset("case.control.example.zarr")
>>> ds.load()
<xarray.Dataset>
Dimensions:           (alleles: 2, alt_alleles: 1, samples: 1, variants: 72)
Dimensions without coordinates: alleles, alt_alleles, samples, variants
Data variables: (12/15)
call_AF           (variants, samples, alt_alleles) float32 0.6238 ... 0.1296
call_ES           (variants, samples, alt_alleles) float32 -8.975e-07 ......
call_EZ           (variants, samples, …
```
=> Make VCF genotypes optional

requirements.txt, setup.cfg
Fixes #617 until the next release of fsspec which should contain a fix for the underlying issue (see linked issue in #617)
=> Exclude fsspec versions causing intermittant test failures

docs/user_guide.rst, sgkit/io/bgen/bgen_reader.py, sgkit/io/utils.py, sgkit/io/vcf/utils.py, sgkit/io/vcf/vcf_reader.py, sgkit/io/vcfzarr_reader.py, sgkit/tests/io/vcf/test_utils.py, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/test_regenie.py
Fixes #615.
This uncovered a bug, where VCF part files with no variants were not being written, which manifested as an error with the new version of Xarray when it tried to consolidate their metadata. This change includes a fix so that empty part files are written (containing zero variants).
=> Xarray consolidate metadata change

setup.cfg, sgkit/io/bgen/bgen_reader.py, sgkit/io/plink/plink_reader.py, sgkit/io/utils.py, sgkit/io/vcf/vcf_partition.py, sgkit/stats/hwe.py, sgkit/stats/ld.py, sgkit/stats/popgen.py, sgkit/stats/regenie.py, sgkit/stats/utils.py, sgkit/testing.py, sgkit/tests/io/bgen/test_bgen_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/test_mis.py, sgkit/tests/test_pc_relate.py, sgkit/tests/test_pca.py, sgkit/tests/test_popgen.py, sgkit/tests/test_regenie.py, sgkit/tests/test_stats_utils.py, sgkit/tests/test_testing.py, sgkit/tests/test_vcfzarr_reader.py, sgkit/utils.py, sgkit/window.py, validation/gwas/method/pc_relate/validate_pc_relate.py
* Ignore 'no-untyped-call' mypy errors in tests, due to large number of NumPy false positives.
* Use new NDArray generic type.
* Ignore new NumPy false positive errors.
* 
Fixes #631
=> Fix type checking errors as a result of using NumPy 1.21.0

sgkit/io/utils.py, sgkit/io/vcf/__init__.py, sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/io/vcf/test_vcf_roundtrip.py
Fixes #487. The maximum number of alleles found while parsing is stored in `ds.attrs["max_alt_alleles_seen"]` (in all cases).
=> Issue a warning if the number of alt alleles exceeds the maximum specified

.github/workflows/windows.yml, requirements.txt, setup.cfg
Fixes #654.
This is a point fix, which may break again when Numba 0.54.1 is released - but we should probably re-evaluate at that point (since it is possible that Numba will support NumPy 1.21 at that point).
=> Don't use Numba 0.54.0 since it doesn't work with NumPy 1.21

docs/api.rst
Trivial fix for missing docs for `pbs` on https://pystatgen.github.io/sgkit/latest/api.html
=> Add missing pbs API docs

sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/data/all_fields.vcf, sgkit/tests/io/vcf/test_vcf_generator.py, sgkit/tests/io/vcf/test_vcf_lossless_conversion.py, sgkit/tests/io/vcf/test_vcf_writer.py, sgkit/tests/io/vcf/vcf_generator.py, sgkit/tests/io/vcf/vcf_writer.py
Fixes #773 
There's quite a lot of code here, but most of it is test code, including:
* code to generate a VCF file (_all_fields.vcf_) with all the different possible field types
* code to canonicalise a VCF file to make text comparison possible
* code to write VCFs from VCF Zarr format
The non-test changes are fixes to handle edge cases in converting the different field types.
=> Test conversion VCF -> VCF Zarr -> VCF is lossless

requirements-doc.txt
More churn in the doc packages (scanpydoc was upgraded to require latest sphinx_autodoc_typehints).
=> Upgrade sphinx_autodoc_typehints to fix doc build

requirements.txt, setup.cfg
=> Pin pandas < 1.4.0 since statsmodels doesn't support this version yet.

.pre-commit-config.yaml, requirements-dev.txt, requirements-doc.txt, setup.cfg, sgkit/stats/aggregation.py, sgkit/stats/association.py, sgkit/stats/ld.py, sgkit/stats/popgen.py
=> Pin cyvcf2

requirements-dev.txt, requirements.txt, setup.cfg
Fixes #820.
Also remove the Dask pin as that was imposed by rechunker == 0.3.0.
=> Unpin rechunker now that version 0.5.0 is out

requirements.txt, setup.cfg, sgkit/stats/ibs.py, sgkit/tests/test_ibs.py
Fixes #836
AFAICT the upstream bug was fixed in dask version 2022.01.0, so the new tests will fail on older versions
=> Allow chunking in the samples dimention for identity_by_state

requirements.txt, setup.cfg, sgkit/io/bgen/bgen_reader.py
This is related to #818 (following up now that statsmodels is fixed). I also needed to fix a call to `from_delayed`, discussed here: https://github.com/dask/dask/issues/5435.
=> Remove Pandas pin on < 1.4.0

sgkit/stats/aggregation.py, sgkit/stats/popgen.py, sgkit/stats/utils.py, sgkit/tests/test_aggregation.py, sgkit/tests/test_popgen.py, sgkit/tests/test_stats_utils.py, sgkit/variables.py
Fixes #730
Adds four generic cohort reductions `cohort_sum`, `cohort_nansum`, `cohort_mean` and `cohort_nanmean`. Also updates `count_cohort_alleles` and `observed_heterozygosity` to use these functions. These functions aim to mimic standard numpy functions with regard to return dtypes (on Linux)  which results in `count_cohort_alleles` returning `uitn64` rather than `int32`. The changes also makes `count_cohort_alleles` more flexible in terms of chunking of the input `call_allele_count` array and, based on some simple benchmarks, there is a moderate performance improvement.
=> Generic functions for cohort sums and means

sgkit/stats/aggregation.py, sgkit/stats/popgen.py
=> Avoid unnecessary task dependencies by using numpy arrays

requirements-doc.txt
Fixes #876.
I managed to build this locally and view the new blog.
=> Pin version of ablog to avoid build error

sgkit/accelerate.py, sgkit/distance/metrics.py, sgkit/stats/aggregation.py, sgkit/stats/conversion.py, sgkit/stats/hwe.py, sgkit/stats/ld.py, sgkit/stats/pedigree.py, sgkit/stats/popgen.py, sgkit/stats/utils.py, sgkit/utils.py
Fixes #371 and #869 
This is just a suggestion and I'm not sure of the best way to test this in CI unless we create an additional runner?
=> Toggle numba caching by environment variable

requirements.txt, setup.cfg
Change numpy pin now that numba supports numpy 1.22 (but not 1.23)
I'm hoping this will help with fixing the wheels build (https://github.com/pystatgen/sgkit/actions/runs/2816635903) by allowing a later version of cyvcf2 to be used that has Python 3.10 Mac wheels.
Fixes #857
=> Remove scikit-learn pin

.github/workflows/wheels.yml
Fixes #887 by excluding the test, until the upstream cyvcf2 issue is fixed.
=> Exclude wheels test on macOS Python 3.10

docs/api.rst, sgkit/__init__.py, sgkit/stats/pedigree.py, sgkit/tests/test_pedigree.py, sgkit/variables.py
Fixes #858
This method computes the pedigree estimate of expected inbreeding without requiring computation of a full kinship matrix as an intermediate. This significantly reduces RAM usage and is (usually) faster than calculating the full kinship matrix. However, the exact difference in resource usage depends on pedigree complexity. There also seems to be some added overhead which I think stems from using dicts within numba. I chose to only implement the full Hamilton-Kerr method for both diploids and polyploids. This leaves some performance on the table for diploids, but I don't think it's significant enough to justify a specific implementation.
I did some simple benchmarking using randomly generated pedigrees which I'd expected to be close to the worst-case scenario for the new method …
=> Pedigree inbreeding

requirements.txt, setup.cfg, sgkit/tests/test_utils.py, sgkit/utils.py
This fixes #890 by special casing zero-dimensional arrays.
BTW I'm not sure if there's a bug in Dask or not. Here's the shortest reproducible example I've found so far:
```
>>> import numpy as np
>>> import dask.array as da
>>> x = np.array("hi")
>>> d = da.array(x)
>>> lens = np.frompyfunc(len, 1, 1)(d)
>>> lens.compute()
2
>>> lens.max().compute()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/tom/miniconda3/envs/sgkit-dev-3.8/lib/python3.8/site-packages/dask/base.py", line 315, in compute
(result,) = compute(self, traverse=False, **kwargs)
File "/Users/tom/miniconda3/envs/sgkit-dev-3.8/lib/python3.8/site-packages/dask/base.py", line 600, in compute
results = schedule(dsk, keys, **kwargs)
File …
```
=> Fix max str len for dask

docs/api.rst, sgkit/__init__.py, sgkit/stats/pedigree.py, sgkit/tests/test_pedigree.py, sgkit/variables.py
Fixes #897
This method uses the same approach as `pedigree_inbreeding` to calculate only a minimal subset of kinship values required for the inverse relationship matrix. Currently this method is still returning a dense matrix (as opposed to a sparse matrix), so the potential memory reduction isn't realized. However, it should be simple to generalize this code to a sparse encoding if/when required.
With some simple benchmarking using real pedigrees of approx 6500 samples (mentioned in #891) I'm seeing approximately a 3x speed up relative to the `pedigree_kinship` method which was a dependency of the old `inverse_additive_relationships` method. However, this speed up will depend on pedigree structure.
One of the changes in this PR is that the internal `inbreeding_Hamilton_Kerr` method now …
=> Replace inverse_additive_relationships with pedigree_inverse_relationship

sgkit/stats/popgen.py, sgkit/tests/test_utils.py, sgkit/tests/test_variables.py, sgkit/utils.py, sgkit/variables.py
This is a proof of concept for #904.
It adds the option of named dimensions to `ArrayLikeSpec`. Individual dims can be optional, have multiple valid names, or be unnamed using a wildcard ("*"). 
If `dims` is specified without `ndim` then `ndim` will be calculated from `dims`. If they are both specified then they are checked for congruence. Dimension names are checked as part of variable validation and a `DimensionWarning` is given if the observed `dims` don't match the spec. A `DimensionWarning`  is also given if a spec is so vague that there is more than one possible mapping of array dims to spec dims (this is only possible with multiple optional dims and isn't an issue for any current variables).
I've possibly been a bit heavy handed with adding named dimensions to variables and some of …
=> Add dimension names to ArrayLikeSpec

sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py
I'm working with TB VCF files, some of which have ~2000 alt alleles, requiring a high `max_alt_alleles` argument to `vcf_to_zarr`. 
It seems VCF performance scales very poorly with this parameter.
Profiling showed that 40% of this time was spent running `max` in `vcf_to_zarr_sequential`, as `max` is called with a `max_alt_alleles` length array for each variant. However the result of this operation isn't used (as far as I could tell) so this PR removes those lines.
=> Remove unused max length calculations

docs/vcf.rst, sgkit/io/vcf/__init__.py, sgkit/io/vcf/utils.py, sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/test_utils.py, sgkit/tests/io/vcf/test_vcf_lossless_conversion.py, sgkit/tests/io/vcf/test_vcf_reader.py
This implements some of the findings in #925
* Adds Delta encoding (filter) for VCF POS fields
* Issue a warning if there are float FORMAT fields with no filters set
* Adds a section of documention to the VCF covering compression, and giving an example of how to truncate float fields to 2dp. 
* 0efd28a7826aac6b14f74bedd41ab880338eb8f2 is a fix for a bug where if you specify the filters for a dataset variable then the default sgkit compressor is ignored since the dictionaries weren't being merged correctly.
I considered always rounding FORMAT float fields to 2dp, but there are problems with NaN (can't use FixedScaleOffset since it doesn't preserve NaNs) and precision (which integer type to use for FixedScaleOffset depends on the range of the values).
Quantize and Bitround do better here …
=> Improve default VCF compression

sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py
From #941.
For VCFs with a small number of samples, a Zarr chunk size of 1000 was being used by default which was wasteful and slow. This change limits the chunk size to the number of samples.
=> Ensure chunking is not excessive in samples dimension.

sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/io/vcf/test_vcf_roundtrip.py
Part of #464, and needed for https://github.com/tskit-dev/tsinfer/pull/748
=> Add `contig_lengths` dataset attribute if found in the VCF file

sgkit/io/vcf/vcf_writer.py, sgkit/io/vcf/vcf_writer_utils.py, sgkit/tests/io/vcf/data/min_fields.vcf, sgkit/tests/io/vcf/test_vcf_lossless_conversion_new.py, sgkit/tests/io/vcf/test_vcf_writer.py, sgkit/tests/io/vcf/test_vcf_writer_utils.py
This is a first draft of a `zarr_to_vcf` function that uses numba to get good performance (#924).
- I can get ~100MB/s write speed for the benchmark in https://github.com/pystatgen/sgkit/pull/944 which uses a real VCF file.
- Relies on the VCF header stored as a Zarr attribute, so really only useful for roundtripping VCF -> Zarr -> VCF at the moment.
- It passes some, but not all, of the "lossless" tests that check VCF -> Zarr -> VCF is unchanged.
- Float values are written using the `ftoa` function, which does not have the same output as the htslib implementation in some cases. For example, it has different rules around number of decimal places, and doesn't support exponential notation. This could be improved, but it will be hard to make it match exactly. This is why some of the …
=> VCF writer using numba

.cirun.yml, .github/workflows/build-gpu.yml
The `workflow` and `count` parameters are deprecated, we just use labels now to runner matching. The multiple regions option is added for fallback, so that instance spinup is more guaranteed. This was earlier done implicitly but we made this explicitly recently, hence a required change now. Regarding the `github.run_id` suffix in `runs-on` param here is the [doc](https://docs.cirun.io/reference/unique-runner-labels).
cc @tomwhite @ravwojdyla
=> Update cirun config for the latest api

benchmarks/benchmarks_vcf.py, conftest.py
This is an [`asv`](https://asv.readthedocs.io/) version of #944.
We discussed moving away from `asv` in #938, but alternatives like `pytest-benchmark` don't allow metrics that aren't time based. Given that we already publish `asv` benchmarks at https://pystatgen.github.io/sgkit-benchmarks-asv/, I had a go at re-purposing the VCF speed benchmarks in #944 as `asv` benchmarks. This wasn't too hard, and it's possible to run them locally if needed using `asv run` from the `benchmarks` directory.
=> Add asv benchmarks for VCF

benchmarks/benchmarks_vcf.py
This is an `asv` version of #941, which it supersedes.
I've reduced the size of the test file to a more manageable size of 5.5MB (500k lines of vcf).
=> Add asv benchmarks for VCF compression size

sgkit/io/vcf/vcf_reader.py, sgkit/tests/io/vcf/data/info_name_clash.vcf, sgkit/tests/io/vcf/test_hypothesis_vcf.py, sgkit/tests/io/vcf/test_vcf_reader.py
=> Handle variable name clashes in VCF reading

docs/api.rst, docs/changelog.rst, sgkit/io/bgen/bgen_reader.py, sgkit/stats/association.py, sgkit/stats/grm.py, sgkit/stats/ld.py, sgkit/stats/regenie.py, sgkit/tests/test_association.py, sgkit/tests/test_ld.py, sgkit/variables.py
Replaces variable `dosage` with `call_dosage`.
This is a bit more of a breaking change than originally anticipated. The main user facing change is the default argument in the `ld.py` methods. I have also had to generalize the `call_dosage` spec to allow ints and uints. I wonder if there's an elegant way to deprecate a variable from the spec?
[`test_regenie_loco_regression__raise_on_non_2D`](https://github.com/pystatgen/sgkit/blob/main/sgkit/tests/test_association.py#L505) is failing because the incorrect dimensionality is now caught early by variable validation. I could just remove the test but the comment  `# we also cover Q.rechunk(X.chunksize) in this test` suggests that a new test would be required. However, I'm not quite confident I understand the code well enough. Could @pentschev …
=> Deduplicate dosage variables

benchmarks/benchmarks_plink.py
See #926. Write speed is around 30Mb/s for plink:
```shell
asv run --quick --bench plink
· Creating environments
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] · For sgkit commit 9309051d <plink-benchmarks>:
[  0.00%] ·· Benchmarking conda-py3.8
[100.00%] ··· benchmarks_plink.PlinkSpeedSuite.track_write_plink_speed    29.020380729941493
```
=> Add asv benchmark for `write_plink`

sgkit/io/vcfzarr_reader.py
When converting very large VCFs I'm running out of RAM when constructing the task graph for the `concat_zarrs` step. This PR breaks the task graph into the independent steps.
=> Split the concat_zarrs step to avoid very large dask task counts

.github/workflows/build.yml, requirements-dev.txt
The build is breaking due to this (e.g. https://github.com/pystatgen/sgkit/actions/runs/4710629116).
See https://about.codecov.io/blog/message-regarding-the-pypi-package/ for context.
=> Use Codecov GitHub action since the PyPi package has been removed

sgkit/io/vcfzarr_reader.py, sgkit/tests/io/vcf/test_vcf_reader.py
=> Give hint for how to work around Number='.' error when reading VCF

docs/changelog.rst, sgkit/io/vcf/vcf_writer.py, sgkit/model.py, sgkit/tests/io/vcf/test_vcf_roundtrip.py, sgkit/tests/io/vcf/test_vcf_writer.py
Not ready to merge (but happy to discuss) since it doesn't have full coverage yet.
=> Generate VCF header when writing, if no header is explicitly supplied

docs/changelog.rst, sgkit/testing.py, sgkit/tests/test_testing.py
Came across this while trying to save a VCF of a simulated callset - seems like it should be in the simulated set?
=> Add variant id to simulate dataset

sgkit/io/vcf/vcf_writer.py, sgkit/io/vcf/vcf_writer_utils.py, sgkit/stats/pedigree.py, sgkit/testing.py, sgkit/tests/io/vcf/test_vcf_reader.py, sgkit/tests/io/vcf/vcf_writer.py, sgkit/tests/test_preprocessing.py, sgkit/tests/test_testing.py
Now that [Numba 0.57.0 is out](https://github.com/numba/numba/releases/tag/0.57.0) our automated tests are running on NumPy 1.24, which have exposed some deprecation errors, e.g.
```
FAILED sgkit/tests/io/vcf/test_vcf_writer.py::test_write_vcf__add_drop_fields[False] - FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
```
See https://github.com/pystatgen/sgkit/actions/runs/4867183070/jobs/8679511958#step:8:3273
=> NumPy 1.24 fixes

.github/workflows/build.yml, docs/conf.py, docs/examples/index.rst, validation/gwas/method/pc_relate/README.md, validation/gwas/method/pc_relate/run.sh
It's still a bit rough, but I think the key parts are there. This covers working with pedigree data, calculating relationship matrices from pedigree and molecular data, and combining them into a hybrid relationship matrix. It also showcases the flexibility of having sgkit based on xarray.
=> Add tutorial on relationship matrices

.github/workflows/windows.yml, docs/examples/gwas_tutorial.ipynb, docs/how_do_i.rst, requirements-doc.txt, requirements.txt, sgkit/io/bgen/bgen_reader.py, sgkit/io/plink/plink_reader.py
=> Fix main build and windows build

docs/changelog.rst, docs/getting_started.rst, sgkit/stats/aggregation.py, sgkit/stats/aggregation_numba_fns.py, sgkit/stats/popgen.py, sgkit/tests/test_aggregation.py
This updates `variant_stats` to use a pair of gufuncs to calculate variant counts and hom/het genotype counts respectively.
This seems to be the sweet spot for performance, It may be possible to use a single gufunc but I can't seem to maintain the same performance (probably due to the complexity of the inner loop). The two gufunc soultion is also nice for modularity. I also looked at using [`da.apply_gufunc`](https://docs.dask.org/en/stable/generated/dask.array.gufunc.apply_gufunc.html) to have multiple return values but the performance seems to be worse than `map_blocks` with a single return value.
This also changes the `count_variant_alleles` function to give the option of counting alleles from the `call_genotype` array directly rather than via the `call_allele_count` array. This …
=> Improve performance of `variant_stats`

.mergify.yml
The Python 3.8 build on Windows was removed in #1122. This updates the mergify config to reflect that so auto-merge labels work again.
=> Remove Python 3.8 on Windows from mergify config

sgkit/distance/api.py
=> Format matrix in pairwise docs

docs/api.rst
I've had a go at subsections in the method list as it was getting unwieldy.
=> Methods doc categories 

.github/workflows/build.yml, sgkit/io/vcf/vcf_writer_utils.py, sgkit/stats/conversion_numba_fns.py, sgkit/stats/genedrop_numba_fns.py, sgkit/stats/pedigree.py
Leaving `NUMBA_DISABLE_JIT=1` for `test_pedigree.py` which contains many jitted functions.
=> Avoid disabling jit on guvectorised functions 

requirements-dev.txt, requirements.txt, setup.cfg, sgkit/stats/genedrop_numba_fns.py, sgkit/stats/pedigree.py
Fixes #1225
This only fixes a couple of small issues for Numpy 2 compatibility. However, many tests are still failing due to Cython-Numpy 2 compatibility issues. See https://github.com/brentp/cyvcf2/issues/307.
=> Minor fixes for Numpy 2

docs/api.rst, docs/changelog.rst, docs/vcf.rst, sgkit/io/vcf/vcf_partition.py, sgkit/io/vcf/vcf_reader.py, sgkit/io/vcfzarr_reader.py
=> Deprecate functions for reading VCF

.github/workflows/cubed.yml, conftest.py, sgkit/distarray.py, sgkit/stats/aggregation.py, sgkit/tests/test_aggregation.py, sgkit/tests/test_popgen.py
See #908
This takes an alternative approach to the one in #1249, by using `map_blocks` on both Dask and Cubed, rather than Xarray's `apply_ufunc`. This avoids the possible issue of the Dask graph changing (originally from #871) that was seen in #1249 by keeping the Dask code path the same.
I think this is the more pragmatic path forward as it allows us to experiment with Cubed by making minimal changes to Dask. (It also doesn't preclude using `apply_ufunc` in the future.)
Would love to get your thoughts @jeromekelleher and @timothymillar.
=> Run test_count_call_alleles on Cubed (alternative approach)

.github/workflows/check-docs.yml, .github/workflows/wheels.yml
The docs build has been failing since [upload-artifact v2 has been deprecated](https://github.com/actions/upload-artifact)
=> Update actions/upload-artifact to v4 in .github/workflows

.github/workflows/cubed.yml, sgkit/distarray.py, sgkit/stats/aggregation.py, sgkit/stats/hwe.py, sgkit/tests/test_aggregation.py
More progress on #908 - `sample_stats` and `hardy_weinberg_test` now work on Cubed.
=> Use sgkit.distarray for sample_stats and hardy_weinberg_test

.github/workflows/cubed.yml, sgkit/distarray.py, sgkit/stats/association.py, sgkit/stats/utils.py, sgkit/tests/test_association.py
=> Use sgkit.distarray for gwas_linear_regression

sgkit/stats/aggregation.py, sgkit/stats/aggregation_numba_fns.py, sgkit/stats/popgen.py
This is a partial fix for the problem in https://github.com/sgkit-dev/sgkit/issues/1267#issuecomment-2444431520 while we figure out what to do about distance functions.
This can be merged now before we unpin Dask.
=> Don't use local functions to wrap numba functions

.github/workflows/benchmark.yml, .github/workflows/build-gpu.yml, .github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/wheels.yml, .github/workflows/windows.yml, .mergify.yml, docs/changelog.rst, docs/getting_started.rst, requirements-dev.txt, requirements-numpy2-dev.txt, setup.cfg
=> Drop Python 3.9

.github/workflows/build.yml, sgkit/io/bgen/bgen_reader.py, sgkit/io/dataset.py, sgkit/tests/io/bgen/test_bgen_reader.py, sgkit/tests/io/test_dataset.py, sgkit/tests/test_association.py, sgkit/tests/test_regenie.py, sgkit/utils.py
=> Run tests using Zarr Python v3

.github/workflows/build-numpy-2.yml, .github/workflows/build.yml, docs/changelog.rst, sgkit/stats/pedigree.py, sgkit/stats/pedigree_numba_fns.py, sgkit/tests/test_pedigree.py
I've tested this with a real pedigree of ~55,000 individuals on a 4-core laptop in WSL2. I can calculate the pedigree matrix using chunks of 5000 samples and save the chunked matrix to a Zarr store in a total of < 25s using ~2.5GB of RAM. The full matrix would be ~22.5GB which exceeds the memory of this machine.
I've used the `@jitclass` experimental feature from Numba for a simple triangular matrix class. Using a triangular matrix halves the RAM needed for the intermediate matrices. It's not strictly necessary to use `@jitclass` for this but it allows for greater code reuse via custom `__setitem__`/`__getitem__`. If this is an issue it could be reworked to avoid `@jitclass`.
I've also removed the test runs with `NUMBA_DISABLE_JIT: 1` because this introduces a dependency on `@guvectorize` …
=> Simple chunked pedigree kinship

.github/workflows/build.yml, docs/examples/1kg.schema.json, requirements-dev.txt, sgkit/tests/io/test_dataset.py, sgkit/tests/test_testing.py
=> Fix CI for Zarr Python v3

.github/workflows/build-numpy-1.yml, .github/workflows/build.yml, .github/workflows/check-docs.yml, .github/workflows/docs.yml, docs/changelog.rst, requirements-dev.txt, requirements-numpy1-dev.txt, requirements-numpy1.txt, requirements-numpy2.txt, requirements.txt, setup.cfg, sgkit/stats/pca.py
This comes from a request that @benjeffery made in the meeting yesterday. NumPy 2 has been out for a while now, and has proved stable (in other projects), so it makes sense to remove the pin - and make NumPy 2 the default. I've kept tests for NumPy 1.
=> Remove NumPy<2 pin

docs/conf.py, requirements-doc.txt
Add https://sphinx-copybutton.readthedocs.io/en/latest/ to the doc build. This adds a handy button on code snippets that enables copying the entire block
=> doc: add copybutton to code snippets

.github/workflows/wheels.yml
Should fix. I also added a line to run the action on PRs so it can be tested here. Can remove before merging..
=> build: adjust github action for pyproject.toml

.github/workflows/build.yml, docs/examples/1kg.schema.json, docs/examples/gwas_tutorial.ipynb, requirements-dev.txt, requirements-numpy1-dev.txt, sgkit/tests/io/test_vcf2zarr_compat.py
New version of #1309 now that bio2zarr 0.1.6 has been released.
=> Fix vcf2zarr tests

docs/api.rst, docs/changelog.rst, sgkit/io/plink/__init__.py, sgkit/io/plink/plink_reader.py, sgkit/io/plink/plink_writer.py
=> Deprecate plink functions

docs/changelog.rst, sgkit/io/bgen/bgen_reader.py
This will allow us to remove the rechunker dependency later on.
Rechunker may be deprecated at some point, see https://github.com/pangeo-data/rechunker/issues/160. Also, we have had build issues due to Xarray and Rechunker version incompatibilities, so it would be good to remove another dependency.
=> Deprecate `rechunk_bgen` that uses rechunker 
