sgkit-dev/sgkit

.github/workflows/build.yml
.pre-commit-config.yaml
README.md
requirements-dev.txt
requirements.txt
setup.cfg
sgkit/__init__.py
sgkit/core.py
sgkit/tests/test_core.py

This uses the tools discussed in #5, except Coveralls (it does test code coverage though).
The actual code and the test are just for illustration and would be replaced by something more realistic later, such as that being discussed in other issues and in https://discourse.smadstatgen.org/t/xarray-conventions-for-variation-data/44/4.
The settings are intentionally strict: code coverage has to be 100%, and mypy is run with the `--strict` option. The latter may have to be relaxed in the future, but let's see how far we can get with it.
Comments and suggestions welcome of course.

Enforce coding standards

---

.github/workflows/build.yml
.pre-commit-config.yaml
README.md
requirements-dev.txt

Follow up to #39 and #46. Right now requires duplication of requirements, I've opened https://github.com/pre-commit/mirrors-mypy/issues/23

Add mypy to precommit

---

sgkit/api.py
sgkit/stats/aggregation.py
sgkit/stats/association.py
sgkit/testing.py
sgkit/tests/test_aggregation.py
sgkit/tests/test_api.py
sgkit/tests/test_association.py

Changes for https://github.com/pystatgen/sgkit/issues/81.

Removing slash from variable names

---

sgkit/stats/aggregation.py
sgkit/tests/test_aggregation.py

https://github.com/pystatgen/sgkit/issues/79

Fix count alleles bug for axis 1 chunking

---

.pre-commit-config.yaml
setup.cfg

https://github.com/pystatgen/sgkit/issues/105

Adding zarr dep

---

docs/contributing.rst

Add pr/git ops doc

---

docs/contributing.rst

Add initial dev conventions (for tests)

---

.pre-commit-config.yaml
setup.cfg

https://github.com/pystatgen/sgkit/issues/120

Add numba dep

---

.mergify.yaml

Add mergify test flight

---

.mergify.yml
docs/contributing.rst

Re: #127, #107 
* mergify requires at least one +1 from @pystatgen/committers 
* mergify will remove stale reviews

Update mergify config after weekly

---

sgkit/api.py
sgkit/tests/test_api.py

Small but necessary changes for https://github.com/pystatgen/sgkit-bgen/issues/13

Adding support for genotype probabilities in dosage dataset

---

.github/workflows/build.yml
setup.cfg

Change minimum Python version to 3.7.

---

.mergify.yml

Remove "remove outdated reviews" from mergify.

---

.github/workflows/docs.yml

Install GSL in doc publish workflow as well

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/validation.yml
README.md

Add badges for build/doc and validation

---

setup.cfg

Add fsspec to 'vcf' extras

---

docs/contributing.rst

Fixes #263
cc @tomwhite @ravwojdyla

Add instructions to install GSL

---

sgkit/io/bgen/bgen_reader.py

Closes https://github.com/pystatgen/sgkit/issues/323

Simplify `read_metafile`

---

docs/contributing.rst

Fix forum URL

---

sgkit/testing.py
sgkit/tests/test_testing.py

Closes https://github.com/pystatgen/sgkit/issues/139

Change simulated contig names to be python ints

---

docs/api.rst
sgkit/io/plink/plink_reader.py
sgkit/io/vcfzarr_reader.py
sgkit/stats/aggregation.py
sgkit/testing.py

Also add simulate_genotype_call_dataset to public API.
Fixes #252

Remove create_*_dataset methods from public API.

---

sgkit/io/bgen/bgen_reader.py
sgkit/io/plink/plink_reader.py
sgkit/io/vcf/vcf_reader.py
sgkit/io/vcfzarr_reader.py
sgkit/model.py
sgkit/testing.py
sgkit/tests/test_model.py
sgkit/tests/test_popgen.py

Straightforward rename (easier now all repos are in one).
Fixes #320

Rename 'variant_alleles' to 'variant_allele'

---

sgkit/distance/api.py

Addressing some minor comments from here: https://github.com/pystatgen/sgkit/pull/306#issuecomment-714635731
cc @alimanfoo @eric-czech

Nitpicks from the pairwise distance PR

---

sgkit/stats/popgen.py

Make Tajimas_D lazy again

---

docs/contributing.rst
sgkit/__init__.py
sgkit/io/bgen/__init__.py
sgkit/io/plink/__init__.py
sgkit/io/vcf/__init__.py

Document init/__all__ usage

---

sgkit/tests/test_utils.py
sgkit/utils.py

Include attributes when merging datasets

---

MANIFEST.in
docs/getting_started.rst
docs/user_guide.rst
docs/vcf.rst
requirements-dev.txt
requirements.txt
setup.cfg
sgkit/__init__.py
sgkit/io/bgen/__init__.py
sgkit/io/plink/__init__.py
sgkit/io/vcf/__init__.py

Changes needed to perform the release, see #367

Release 0.1.0a1

---

.github/workflows/windows.yml

Update setup-miniconda action to v2

---

docs/vcf.rst

Issue #379
Is this what you had in mind @tomwhite ?
I'm not sure if its worth getting into the nitty-gritty of different sentinel values here.
Likewise I think it's a good idea to highlight that it is still necessary for the user to understand the type of polyploidy present in their data.

Document polyploid and mixed-ploidy VCF support #379

---

sgkit/stats/association.py
sgkit/tests/test_association.py

Closes https://github.com/pystatgen/sgkit/issues/219

Make gwas p values lazy 

---

sgkit/variables.py

I introduced this by accident in #389

Remove spurious print

---

sgkit/stats/association.py
sgkit/tests/test_association.py

Closes #397 
I'm not sure how this passed the tests -- I'll have a look and see if a new test would catch it.
**UPDATE**: The tests were passing because the dataset had no chunking, so I added a test that forces chunking.

Fix linear_regression

---

sgkit/stats/aggregation.py
sgkit/tests/test_aggregation.py

Ignore samples that are not in any cohort

---

sgkit/stats/popgen.py
sgkit/tests/test_popgen.py

Divergence should handle case when all calls for a cohort are missing

---

sgkit/io/vcf/vcf_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py

Pass ploidy arguments to vcf_to_zarr_parallel  #409

---

sgkit/stats/preprocessing.py
sgkit/tests/test_preprocessing.py

Mixed-ploidy filter_partial_calls #414

---

docs/vcf.rst
sgkit/io/utils.py
sgkit/io/vcf/vcf_partition.py
sgkit/io/vcf/vcf_reader.py
sgkit/tests/io/vcf/test_vcf_partition.py
sgkit/tests/io/vcf/test_vcf_reader.py

Add target_part_size to vcf_to_zarr

---

.github/workflows/build.yml
.github/workflows/docs.yml
docs/vcf.rst

Remove requirement to install libcurl for cyvcf2

---

.github/workflows/build.yml
.github/workflows/windows.yml

Run build on a schedule #422

---

.github/scripts/upstream_install.py
.github/workflows/upstream.yml
README.md

Re #444
This is right now draft, wanna get some feedback on the approach before polishing.

Add upstream CI

---

sgkit/stats/association.py

See discussion in https://github.com/pystatgen/sgkit/issues/390#issuecomment-768332568.

Adjust chunksize in gwas_linear_regression to reduce data transfer between workers

---

.github/workflows/build.yml
.github/workflows/upstream.yml
.github/workflows/validation.yml
.github/workflows/windows.yml

Disable scheduled build/windows and validation CI on forks

---

sgkit/display.py
sgkit/tests/test_display.py

Only use variant or sample IDs in display_genotypes if they are unique

---

.pre-commit-config.yaml
sgkit/io/bgen/bgen_reader.py
sgkit/io/dataset.py
sgkit/io/utils.py
sgkit/io/vcfzarr_reader.py
sgkit/stats/pca.py
sgkit/tests/io/bgen/test_bgen_reader.py
sgkit/tests/io/plink/test_plink_reader.py
sgkit/tests/io/test_dataset.py
sgkit/tests/test_aggregation.py
sgkit/tests/test_association.py
sgkit/tests/test_conversion.py
sgkit/tests/test_pca.py

Fix mypy errors with Xarray 0.17.0

---

sgkit/stats/aggregation.py
sgkit/tests/test_aggregation.py
sgkit/variables.py

See #416 
Ac ouple of notes:
- I don't know what I'm missing to populate the "comment" attribute in the HTML REPR?
- I think 'infer' is a better verb than 'impute' in this case.

Add ploidy summary functions #416

---

sgkit/io/vcfzarr_reader.py

See https://github.com/pystatgen/sgkit/issues/388#issuecomment-792962331

Attempt to fix race condition setting Zarr array attributes

---

README.md

Add asv benchmark badge on README

---

sgkit/io/vcf/vcf_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py

Field parsing should use supplied max_alt_alleles #507

---

sgkit/stats/association.py
sgkit/tests/test_association.py

In gwas_linear_regression allow empty covariates #509

---

requirements-dev.txt
setup.cfg

Rechunker 0.4 is causing build failures #530

---

.github/workflows/benchmark.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/upstream.yml
docs/contributing.rst
requirements-dev.txt
requirements-doc.txt
sgkit/tests/test_popgen.py

Minimal updates to use the msprime 1.0 release, and update our testing code the use the new APIs (which generate more suitable data for us).
I hit two separate issues while doing this. I suggest we file issues for these, and merge this much @tomwhite?
There's more we can do in terms of generating cohorts more realistically, but these should probably be done in follow-ups.

Updates for msprime 1.0

---

sgkit/tests/test_popgen.py

Fix precision issue in Fst tests.

---

sgkit/stats/popgen.py
sgkit/tests/test_popgen.py

Fix issues in Tajima's D calculation

---

sgkit/stats/ld.py
sgkit/tests/test_ld.py

New version of #536 following the main branch rename.

Rogers Huff R

---

sgkit/stats/popgen.py
sgkit/tests/test_popgen.py

Handle samples with no cohort in observed_heterozygosity

---

docs/api.rst
sgkit/stats/aggregation.py
sgkit/stats/popgen.py
sgkit/variables.py

Fixes #570. This just adds the missing variable, since we already have some documentation about sample cohorts: https://pystatgen.github.io/sgkit/latest/getting_started.html#cohorts

Add sample_cohort variable #570

---

docs/api.rst
docs/getting_started.rst
docs/user_guide.rst

Document behaviour of intermediate variables

---

docs/getting_started.rst
docs/user_guide.rst
docs/vcf.rst

Document installation using conda

---

validation/gwas/method/pc_relate/validate_pc_relate.py

Follow up from: #587, issue: #554

Fixup validation pc_relate, adjust PCs

---

sgkit/stats/popgen.py
sgkit/tests/test_popgen.py
sgkit/variables.py

Windowing not implemented for Tajima's D #563

---

setup.cfg
sgkit/io/vcf/vcf_reader.py
sgkit/io/vcfzarr_reader.py
sgkit/tests/io/vcf/data/simple.output.mixed_depth.likelihoods.vcf
sgkit/tests/io/vcf/test_vcf_reader.py
sgkit/tests/test_distance.py

Support Number=G VCF fields

---

setup.py

Update setup.py so that GitHub dependency graph works properly #630

---

sgkit/stats/popgen.py

Fix type error in diversity and Tajimas_D.

---

setup.cfg
sgkit/io/vcf/vcf_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py

Add compressor option to VCF functions.

---

docs/api.rst
sgkit/__init__.py
sgkit/stats/aggregation.py
sgkit/tests/test_aggregation.py
sgkit/variables.py

Add method call_allele_frequencies

---

.pre-commit-config.yaml
sgkit/stats/popgen.py
sgkit/tests/test_aggregation.py

Due to recent changes in NumPy, some of mypy checks were failing which are being fixed here.
Fixes https://github.com/pystatgen/sgkit/issues/663

Update pre-commit to numpy>=1.21.2

---

docs/contributing.rst

Document Graphviz dot requirement for building docs.

---

sgkit/io/vcfzarr_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py
sgkit/tests/io/vcf/test_vcf_roundtrip.py

Generate dimension names for fixed-sized Number fields > 1

---

sgkit/io/bgen/bgen_reader.py
sgkit/io/plink/plink_reader.py
sgkit/io/vcfzarr_reader.py
sgkit/testing.py
sgkit/tests/test_ibs.py
sgkit/tests/test_popgen.py

Add type annotations to satisfy latest mypy

---

sgkit/io/utils.py
sgkit/io/vcf/vcf_reader.py
sgkit/io/vcfzarr_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py
sgkit/tests/io/vcf/test_vcf_roundtrip.py

Use missing and fill values from BCF

---

.pre-commit-config.yaml
requirements-doc.txt
sgkit/display.py
sgkit/io/bgen/bgen_reader.py
sgkit/io/utils.py
sgkit/stats/pca.py
sgkit/tests/test_association.py
sgkit/tests/test_pca.py

Fix new mypy errors

---

docs/api.rst
sgkit/io/vcf/vcf_reader.py
sgkit/stats/aggregation.py
sgkit/tests/io/vcf/test_vcf_reader.py
sgkit/variables.py

Rename 'call_genotype_non_allele' to 'call_genotype_fill'

---

sgkit/tests/io/vcf/test_vcf_reader.py

New warning in cyvcf2 causes tests to fail

---

requirements.txt
setup.cfg

Upgrade Dask to address security bug #780

---

docs/api.rst
docs/vcf.rst
sgkit/__init__.py
sgkit/io/vcfzarr_reader.py
sgkit/tests/io/vcf/test_vcf_roundtrip.py
sgkit/tests/test_vcfzarr_reader.py

Rename read_vcfzarr to refer to scikit-allel

---

requirements-doc.txt

Fix doc build

---

sgkit/tests/test_window.py
sgkit/window.py

Add step argument to allow equally-spaced overlapping windows.

---

.mergify.yml

Mergify strict mode deprecation

---

requirements.txt
setup.cfg
sgkit/stats/ld.py
sgkit/tests/test_ld.py

Upgrade to numba 0.55.0

---

requirements.txt
setup.cfg

Add scikit-learn dependency

---

.github/workflows/upstream.yml

Fixes #807
See https://github.com/actions/setup-python/issues/160

Quote Python version numbers in yaml for upstream

---

.github/workflows/upstream.yml
requirements.txt
setup.cfg

Pin numpy < 1.22 since numba 0.55 doesn't work with later versions

---

.pre-commit-config.yaml
requirements.txt
setup.cfg
sgkit/__init__.py
sgkit/io/bgen/bgen_reader.py
sgkit/io/utils.py
sgkit/stats/pca.py
sgkit/stats/popgen.py
sgkit/stats/regenie.py
sgkit/tests/test_association.py
sgkit/tests/test_distance.py
validation/gwas/method/regenie/glow_wgr.py

Fixes #825.
I have turned off mypy's strict mode since it was having so many problems with imports. I've fixed the remaining errors, but I do wonder whether we are getting much value from mypy. Are we doing it wrong, or do other projects have to work as hard to keep the build working?

Upgrade mypy to latest version. Turn off strict mode.

---

.github/workflows/validation.yml

https://github.com/pystatgen/sgkit/issues/832

Fix gcloud tag

---

requirements.txt

Exclude broken zarr versions, due to #828

---

docs/api.rst
sgkit/__init__.py
sgkit/stats/pedigree.py
sgkit/tests/test_pedigree.py
sgkit/variables.py

Add basic pedigree schema

---

sgkit/stats/pedigree.py
sgkit/tests/test_pedigree.py

Work in progress, see discussion in #844

Topological argsort

---

docs/conf.py

Clean up top bar in docs

---

sgkit/io/dataset.py
sgkit/tests/io/vcf/test_vcf_reader.py

Remove VLenUTF8 from filters to avoid double encoding error

---

.pre-commit-config.yaml
requirements.txt
setup.cfg
sgkit/cohorts.py
sgkit/distance/api.py
sgkit/io/plink/plink_reader.py
sgkit/io/vcfzarr_reader.py
sgkit/stats/association.py
sgkit/stats/popgen.py
sgkit/stats/regenie.py
sgkit/tests/test_distance.py
sgkit/utils.py

Fixes the latest set of build failures.

Fix mypy errors

---

.pre-commit-config.yaml

Remove mypy check in precommit

---

sgkit/stats/ibs.py
sgkit/tests/test_ibs.py

Fix numpy input for Weir_Goudet_beta

---

docs/conf.py
docs/index.rst
docs/news.rst
docs/news/introducing_sgkit.md
requirements-doc.txt

Fixes #682
Not ready for merge since we need some content in the first post.

Add news pages

---

.github/workflows/build.yml
.github/workflows/wheels.yml
.github/workflows/windows.yml
docs/getting_started.rst
setup.cfg

Test on Python 3.10

---

.github/workflows/wheels.yml
setup.cfg

Fix windows wheels tests

---

sgkit/io/vcf/vcf_reader.py
sgkit/tests/io/vcf/test_utils.py

Fix get_region_start to work with contig names that have colons and dashes.

---

docs/api.rst
sgkit/__init__.py
sgkit/stats/pedigree.py
sgkit/tests/test_pedigree.py
sgkit/variables.py

Replace additive_relationships with pedigree_relationship

---

sgkit/stats/pedigree.py
sgkit/tests/test_pedigree.py

Use Literal type for pedigree methods

---

sgkit/stats/pedigree.py
sgkit/tests/test_pedigree.py
sgkit/variables.py

Allow use of Hamilton-Kerr methods with parents dim > 2

---

requirements.txt
setup.cfg

Fixes #917 
Successfully tested the [main build](https://github.com/tomwhite/sgkit/actions/runs/3157098558) and the [wheels build](https://github.com/tomwhite/sgkit/actions/runs/3157098557).

Remove NumPy pin

---

.cirun.yml
.github/workflows/build-gpu.yml
.github/workflows/build.yml
.github/workflows/upstream.yml
.github/workflows/wheels.yml
.github/workflows/windows.yml
.mergify.yml
docs/getting_started.rst
requirements-dev.txt
setup.cfg
sgkit/io/vcfzarr_reader.py

Remove python 3.7

---

sgkit/stats/grm.py
sgkit/tests/test_grm.py

Correct ancestral_frequency name in VanRaden GRM ValueError

---

requirements-doc.txt

Pin xarray due to #934

---

docs/api.rst
docs/getting_started.rst
sgkit/__init__.py
sgkit/tests/test_popgen.py
sgkit/window.py

Add `window_by_genome`

---

sgkit/io/vcf/vcf_writer.py
sgkit/tests/io/vcf/test_vcf_writer.py

Process input in chunks in VCF writer

---

docs/changelog.rst
sgkit/io/dataset.py
sgkit/tests/io/test_dataset.py

Add auto_rechunk to save_dataset

---

docs/user_guide.rst

Document SGKIT_DISABLE_NUMBA_CACHE variable #869

---

docs/api.rst
docs/changelog.rst
docs/user_guide.rst
sgkit/io/plink/__init__.py
sgkit/io/plink/plink_writer.py
sgkit/tests/io/plink/test_plink_writer.py

Output plink

---

sgkit/stats/pca.py

Fixes build failure https://github.com/pystatgen/sgkit/actions/runs/4169329268/jobs/7217169173#step:8:1384

Fix PCA example output due to upstream change

---

docs/changelog.rst
sgkit/testing.py
sgkit/tests/test_testing.py

Allow `simulate_genotype_call_dataset` to add phasing info

---

docs/changelog.rst
sgkit/stats/ibs.py
sgkit/tests/test_ibs.py

Improve method `identity_by_state`

---

docs/conf.py

Fix Sphinx build for pydata-sphinx-theme 0.13.0

---

docs/changelog.rst
sgkit/io/vcf/vcf_reader.py
sgkit/io/vcfzarr_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py

Add read_chunk_length

---

docs/api.rst
docs/changelog.rst
sgkit/io/vcf/__init__.py
sgkit/io/vcf/vcf_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py

Uses the new function from #1046.

Add `read_vcf` convenience function

---

docs/changelog.rst
sgkit/io/plink/plink_writer.py
sgkit/io/vcf/vcf_reader.py
sgkit/io/vcf/vcf_writer.py
sgkit/model.py
sgkit/testing.py
sgkit/tests/io/plink/test_plink_reader.py
sgkit/tests/io/test_dataset.py
sgkit/tests/io/vcf/test_vcf_reader.py
sgkit/tests/io/vcf/test_vcf_scikit_allel.py
sgkit/tests/test_model.py
sgkit/tests/test_vcfzarr_reader.py
sgkit/tests/test_window.py
sgkit/variables.py
sgkit/window.py

Store contig names in a `contig_id` array

---

docs/api.rst
docs/changelog.rst
sgkit/io/vcf/__init__.py
sgkit/io/vcf/vcf_reader.py
sgkit/tests/io/vcf/test_vcf_reader.py

Make `zarr_array_sizes` run in parallel

---

docs/changelog.rst
sgkit/stats/grm.py
sgkit/tests/test_grm.py

Add skipna option to genomic_relationship

---

docs/api.rst
docs/changelog.rst
sgkit/__init__.py
sgkit/stats/pedigree.py
sgkit/stats/pedigree_numba_fns.py
sgkit/tests/test_pedigree.py
sgkit/variables.py

Pedigree contribution

---

docs/api.rst
docs/changelog.rst
requirements-dev.txt
requirements-doc.txt
sgkit/__init__.py
sgkit/display.py
sgkit/tests/test_display.py

This scales well enough to a couple of thousand samples which is well beyond the limit of legibility.

Add `display_pedigree` method

---

requirements-doc.txt

Add pickleshare as docs requirement to satisfy Sphinx

---

docs/api.rst

I think this is all that is needed for this?
Fixes #1142

Add pairwise_distance to docs

---

docs/api.rst
docs/changelog.rst
sgkit/__init__.py
sgkit/stats/genedrop.py
sgkit/stats/genedrop_numba_fns.py
sgkit/stats/pedigree.py
sgkit/tests/test_genedrop.py

Add gene-drop simulation method

---

.github/workflows/benchmark.yml
.github/workflows/build-gpu.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/wheels.yml
.mergify.yml
docs/getting_started.rst
setup.cfg
sgkit/stats/pca.py
sgkit/stats/regenie.py
sgkit/window.py

Fix xarray repr in doctests

---

.github/workflows/benchmark.yml
setup.cfg

`project@sgkit-dev.org` -> `project@sgkit.dev`

Update project email address

---

requirements.txt
setup.cfg

Avoids breaking when Zarr v3 is released.

Pin to Zarr < 3

---

docs/changelog.rst
sgkit/stats/ibs.py
sgkit/stats/ibs_numba_fns.py
sgkit/tests/test_ibs.py

Add 'matching' method option to identity_by_state

---

.github/workflows/cubed.yml
sgkit/stats/aggregation.py
sgkit/tests/test_aggregation.py

More progress on #908 - `variant_stats` now works on Cubed.

Use sgkit.distarray for count_variant_alleles and variant_stats

---

.github/workflows/build-gpu.yml

Disable failing GPU build

---

sgkit/tests/test_pca.py

Fix Cubed tests by chunking appropriately

---

.github/workflows/cubed.yml
sgkit/tests/test_window.py
sgkit/window.py

See #908
This contains just a part of #1281. It can't be merged until #1284 is fixed.

Use sgkit.distarray for windowing 

---

.github/workflows/wheels.yml

Test wheels on latest GitHub Actions Mac version

---

docs/_static/switcher.json
docs/changelog.rst
pyproject.toml
sgkit/__init__.py

Update sgkit version to follow bio2zarr
